name: Daily FanGraphs Auction Data Scrape

on:
  schedule:
    # Run at 11:00 AM Eastern Time (15:00 UTC during EST, 16:00 UTC during EDT)
    # Using 16:00 UTC to account for EDT (most of baseball season)
    - cron: '0 16 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas
    
    - name: Run scraper
      run: |
        python ac_scrape.py
      env:
        PYTHONPATH: ${{ github.workspace }}
    
    - name: Commit and push data files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ac_data/
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Daily scrape: $(date +'%Y-%m-%d')"
          git push
        fi
    
    - name: Upload data as artifact
      uses: actions/upload-artifact@v4
      with:
        name: auction-data-${{ github.run_number }}
        path: ac_data/
        retention-days: 30 