name: Run SmartStream

on:
  schedule:
    - cron: '0 0 * * *'  # Run every Monday at 00:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ESPN_S2: ${{ secrets.ESPN_S2 }}
      ESPN_SWID: ${{ secrets.ESPN_SWID }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: python smartStream.py
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update SmartStream results" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}